default_index:
    path: /
    defaults: { _controller: "AppBundle:Default:index" }
    methods: GET
default_pruebas:
    path: /pruebas
    defaults: { _controller: "AppBundle:Default:pruebas" }
    methods: POST 
default_login:
    path: /login
    defaults: { _controller: "AppBundle:Default:login" }
    methods: POST 
default_new:
    path: /new
    defaults: { _controller: "AppBundle:User:new" }
    methods: POST
default_edit:
    path: /edit
    defaults: { _controller: "AppBundle:User:edit" }
    methods: POST
default_newtask:
    path: /newtask
    defaults: { _controller: "AppBundle:Task:new" }
    methods: POST
default_eduttask:
    path: /edittask/{id}
    defaults: { _controller: "AppBundle:Task:new", id: null }
    methods: POST 
default_detail:
    path: /detail/{id}
    defaults: { _controller: "AppBundle:Task:task", id: null }
    methods: POST 
default_tasks:
    path: /list
    defaults: { _controller: "AppBundle:Task:tasks"}
    methods: POST 